name: Verify code
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install packages
        run: npm ci
      - name: Build and verify
        run: npm run build && npm run verify
